CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(160);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(160);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'agent';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique ON users(username);

CREATE TABLE IF NOT EXISTS properties (
  id SERIAL PRIMARY KEY
);

ALTER TABLE properties ADD COLUMN IF NOT EXISTS slug VARCHAR(220);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS title VARCHAR(180);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS price NUMERIC(14, 2) DEFAULT 0;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS district VARCHAR(100) DEFAULT 'Siddipet';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS mandal VARCHAR(120);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS village VARCHAR(120);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS property_type VARCHAR(60);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS land_area VARCHAR(100);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS images JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS owner_name VARCHAR(140);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'available';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE properties ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_properties_slug_unique ON properties(slug);
CREATE INDEX IF NOT EXISTS idx_properties_slug ON properties(slug);
CREATE INDEX IF NOT EXISTS idx_properties_location ON properties(mandal, village);
CREATE INDEX IF NOT EXISTS idx_properties_type ON properties(property_type);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_price ON properties(price);

CREATE TABLE IF NOT EXISTS inquiries (
  id SERIAL PRIMARY KEY
);

ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS property_id INTEGER;
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS name VARCHAR(120);
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_inquiries_property_id ON inquiries(property_id);
